version: "2"
run:
  go: "1.24"
  timeout: 5m

linters:
  default: all
  disable:
    - cyclop # We use maintidx to lint function complexity.
    - exhaustruct
    - funlen
    - gocognit # We use maintidx to lint function complexity.
    - gocyclo # We use maintidx to lint function complexity.
    - ireturn # Complain that interface A implementation method return an interface B... it's a requirement of interface A that is unavoidable.
    - mnd # Too picky. For example, it says that 1000 (used in number of ms in one second) is a magic number.
    - noinlineerr # Why couldn't we inline errors ?
    - nonamedreturns # Warn for every named return, not useful.
    - testpackage
    - varnamelen # I think there are too many false-positives.
    - wsl # Superseded by wsl_v5
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: io/ioutil
              desc: ioutil is deprecated starting with Go 1.16
    errorlint:
      errorf-multi: false
    forbidigo:
      exclude-godoc-examples: true
    nolintlint:
      require-specific: true
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
    revive:
      rules:
        - name: package-comments
          disabled: true
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - std-error-handling
    rules:
      - linters:
          - paralleltest
        text: does not use range value in test Run
    paths:
      - doc.go # Ain't no code in here

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - doc.go # Ain't no code in here
